import type { Metadata } from "next";
import AdminProvider from "@/providers/admin_provider";
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };
export default async function AdminLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params : {
    id : string
  }
}>) {

  return (
    <div>
        <AdminProvider>
        {children}
        </AdminProvider>
    </div>
  );
}