import type { Metadata } from "next";
import AdminProvider from "@/providers/admin_provider";
import { getUserId } from "@/app/actions/helpers/get-userId";
import { isSystemAdmin } from "@/utils/permissions";
import { unauthorized } from "next/navigation";
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };
export default async function AdminLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params : {
    id : string
  }
}>) {
  const userId = await getUserId();
  const hasPremission = await isSystemAdmin(userId) ;
  if(!hasPremission) {
      return unauthorized();
  }
  return (
    <div>
        <AdminProvider>
        {children}
        </AdminProvider>
    </div>
  );
}