import type { Metadata } from "next";
import { Inter} from "next/font/google";
import QueryProvider from '@/providers/QueryProvider';

import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
const geistInter = Inter({
    subsets : ['latin'] ,
    weight : ['400','500','900']
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistInter.className}  antialiased`}
      >
        <QueryProvider>
        {children}
        <Toaster />
        </QueryProvider>
      </body>
    </html>
  );
}
