import { Inter} from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { CreatePostDialog } from "@/components/dialogs/post/create-post";
import { AblyClientProvider } from '@/lib/ably';
import { cn } from "@/lib/utils";
const geistInter = Inter({
    subsets : ['latin'] ,
    weight : ['400','500','900']
});
export const metadata = {
  metadataBase: new URL(process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000'),
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn('min-h-screen bg-background font-sans antialiased', geistInter.className)}>
          <AblyClientProvider>
            {children}
            <Toaster />
            <CreatePostDialog />
          </AblyClientProvider>
      </body>
    </html>
  );
}
