import type { Metadata } from "next";
import { Inter} from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { CreatePostDialog } from "@/components/dialogs/post/create-post";
import { auth } from "@/lib/auth";
import { headers } from "next/headers";
import { redirect } from "next/navigation";
import { NextResponse } from "next/server";
const geistInter = Inter({
    subsets : ['latin'] ,
    weight : ['400','500','900']
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistInter.className}  antialiased`}
      >
        {children}
        <Toaster />
        <CreatePostDialog />
      </body>
    </html>
  );
}
