import type { Metadata } from "next";
import Provider from "../../../../../providers/dashboard_provider";
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };
export default async function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    

  return (
    <div>
        <Provider>
        {children}
        </Provider>
    </div>
  );
}