import type { Metadata } from "next";
import Provider from "../../../../../providers/dashboard_provider";
import { getUserId, getUserIdSafe } from "@/app/actions/helpers/get-userId";
import {isCommunityModerator,isSystemAdmin} from '@/utils/permissions'
import { unauthorized } from "next/navigation";
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };
export default async function AdminLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params : {
    id : string
  }
}>) {
  const {id} = await params;
    const userId = await getUserIdSafe();
    if(!userId) {
      return unauthorized();
    }
    const hasPremission = await isCommunityModerator(userId,id) ;
    if(!hasPremission) {
        return unauthorized();
    }
  return (
    <div>
        <Provider>
        {children}
        </Provider>
    </div>
  );
}